# https://github.com/lsd-rs/lsd?tab=readme-ov-file#config-file-content
#

color:
  theme: custom
icons:
# @see strftime - date formatting: 7:27 AM 12/06/25
date: "+%l:%M%p %D"
literal: true
recursion:
  depth: 4
ignore-globs:
  - .git
  - .DS_Store
  - .fseventsd
  - .Spotlight-V100
  - .VolumeIcon.icns
