name: local
version: v1
schema: v1
models:
  - name: qwen2.5-coder:1.5b-base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles:
      - autocomplete

  - name: embeddinggemma
    provider: ollama
    model: embeddinggemma:latest
    roles:
      - embed

  - name: nomic-embed-text
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed

  - name: Ollama Autodetect
    provider: ollama
    model: AUTODETECT
